server:
  port: 8080

spring:
  ai:
    model:
      chat: "openai"
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          temperature: 0.5
          model: "gpt-4o-mini"
      embedding:
        options:
          model: "text-embedding-ada-002"
    vectorstore:
      observations:
        log-query-response: true
      pgvector:
        initialize-schema: true

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
